ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
endif::[]

// For preview in VS-Code
ifndef::imagesdir[]
:imagesdir: images
endif::[]

include::header.adoc[]

:bl: pass:p[ +]

== PowerShell examples

The examples in this article will use PowerShell 5.1.1.

=== Terminal

==== Code page

* Change to UTF-8 code page.
+
[source,powershell]
----
chcp 65001
$OutputEncoding = [System.Text.Encoding]::UTF8
----

* Change to ASCII(US-ASCII) code page.
+
[source,powershell]
----
chcp 20127
----

* Change to Shift-JIS code page.
+
[source,powershell]
.Shift-JISのコードページに変更します。
----
chcp 932
----

==== Profile

* https://stackoverflow.com/questions/567650/how-to-reload-user-profile-from-script-file-in-powershell[How to reload user profile from script file in PowerShell - Stack Overflow^]
* https://www.tipsfound.com/windows10/11010[Windows 10 環境変数の一覧と既定値^]

. Get profile path
+
[source,powershell]
----
$PROFILE | Get-Member -Type NoteProperty | Format-Table -Wrap
----
+
----
%HOMEPATH%\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
----

. Create a new profile +
In order to create a profile you need to use the following command.
+
[source,powershell]
----
New-Item -ItemType File -Path $profile -Force
----
+
[NOTE]
Note that the above will replace any existing profile. If you want to ensure that you will not replace any profile that already exists and lose the changes that you have applied already, you can try the below.

. Edit a profile
+
[source,powershell]
----
notepad $profile
----

. No Profile
+
----
PowerShell -NoProfile
----

. Load profile
+
[source,powershell]
----
. $PROFILE
----
+
[source,powershell]
----
. $profile
----

.References
* https://www.sconstantinou.com/powershell-profiles/[PowerShell Profiles - Stephanos Constantinou Blog^] +
  windows powershell Get profile path - Google 検索

==== Change color
* http://fractorium.com/?article=configuring-powershell-in-windows-terminal[Configuring Powershell in Windows Terminal «  Fractorium^]
* https://qiita.com/AWtnb/items/5551fcc762ed2ad92a81[【PowerShell】PsReadLine 設定のススメ - Qiita^] +
  Set-PSReadLineOption - Google 検索

[source,powershell]
----
Get-PSReadLineOption
Set-PSReadLineOption -Colors @{Command = "Black"; Member = "Black"; Number = "Black" }
----

==== Changing the command prompt

[cols="a,a",options="autowidth"]
|===
| Code | Rendered

|
[source,powershell]
----
function prompt {"PS $(get-date)> "}
----
| `PS 08/08/2021 16:14:32> `

|
[source,powershell]
----
function prompt {"PS $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')> "}
----
| `PS 2021-08-08 16:16:33> `

|
[source,powershell]
----
function prompt {"PS $(Get-Date -UFormat '%T')> "}
----
| `PS 16:17:52> `

|
[source,powershell]
.Default
----
function prompt {"PS $pwd> "}
----
| `PS C:\...> `

|
[source,powershell]
.Default
----
function prompt {"PS " + (Split-Path (Get-Location) -Leaf) + "> "}
----
| `PS foo> `


|===

.References
* https://stackoverflow.com/questions/5725888/windows-powershell-changing-the-command-prompt[Windows PowerShell: changing the command prompt - Stack Overflow^] +
  powershell change prompt temporarily - Google Search

==== Turn off the beep

* Windows
+
[source,powershell]
----
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
if (!(Test-Path -Path "$Profile")) {New-Item -ItemType File -Path "$Profile" -Force}
Add-Content -Value "Set-PSReadlineOption -BellStyle None" -Path "$Profile"
----

* Linux
+
[source,powershell]
----
if (!(Test-Path -Path "$Profile")) {New-Item -ItemType File -Path "$Profile" -Force}
Add-Content -Value "Set-PSReadlineOption -BellStyle None" -Path "$Profile"
----

=== Scripting

==== Version

[source,powershell]
----
$PSVersionTable
----

[cols="1a,4" options="autowidth"]
|===
| PSVersion | OS

| 4.0.x     | Windows 8.1, Windows Server 2012 R2
| 5.1.x     | Windows 10, Windows Server 2016, Windows 11, Windows Server 2022
|===

==== Get script location

.How can I get the file system location of a PowerShell script?
The path of a running scripts is::
$PSCommandPath

Its directory is::
$PSScriptRoot

==== Modules

* Load functions
+
[source,powershell]
----
. (Join-Path -Path $PSScriptRoot -ChildPath 'Get-Factorial')

Get-Factorial($Args[0])
----

==== Environment Variables

.References
* https://adamtheautomator.com/powershell-environment-variables/[PowerShell and Environment Variables: A Deep Dive^] +
powershell remove env - Google 検索

* List environment variables
+
[source,powershell]
----
dir env:
----
+
[source,powershell]
----
Get-ChildItem -Path Env:
----
+
[source,powershell]
----
[System.Environment]::GetEnvironmentVariables() | Sort-Object
----

* Get environment variables

** Get value from object
+
[source,powershell]
----
(Get-Item -Path Env:ComputerName).Value
----

** Get content
+
[source,powershell]
----
Get-Content -Path Env:ComputerName
----

** Get property
+
[source,powershell]
----
([Environment]::GetEnvironmentVariables()).COMPUTERNAME
----
+
[source,powershell]
----
([System.Environment]::GetEnvironmentVariables()).COMPUTERNAME
----

* Manage process-level environment variables

** Get process-level environment variable
+
[source,powershell]
----
([System.Environment]::GetEnvironmentVariables([System.EnvironmentVariableTarget]::Process)).TestKey
----

** Set environment variable temporary
+
[source,powershell]
----
$Env:TestKey = 'TestValue'
----
+
[source,powershell]
----
[Environment]::SetEnvironmentVariable('TestKey', 'TestValue')
----
+
[source,powershell]
----
[System.Environment]::SetEnvironmentVariable('TestKey', 'TestValue', [System.EnvironmentVariableTarget]::Process)
----

** Remove environment variable
+
[source,powershell]
----
$Env:TestKey = ''
----
+
[source,powershell]
----
[Environment]::SetEnvironmentVariable('TestKey', '', 'Process')
----
+
[source,powershell]
----
[System.Environment]::SetEnvironmentVariable('TestKey', '', [System.EnvironmentVariableTarget]::Process)
----

* Manage user environment variables

** Get a user environment variable
+
[source,powershell]
----
([Environment]::GetEnvironmentVariables("User")).TestKey
----
+
[source,powershell]
----
([System.Environment]::GetEnvironmentVariables([System.EnvironmentVariableTarget]::User)).TestKey
----
+
[source,powershell]
----
Get-ItemProperty -Path HKCU:\Environment -Name TestKey
----

** Set user environment variable permanently
+
[source,powershell]
----
[System.Environment]::SetEnvironmentVariable('TestKey', 'TestValue', "User")
----

** Remove user environment variable permanently
+
[source,powershell]
----
[Environment]::SetEnvironmentVariable('TestKey', '', "User")
----
+
[source,powershell]
----
[System.Environment]::SetEnvironmentVariable('TestKey', '', [System.EnvironmentVariableTarget]::User)
----

* Manage system environment variables

** Get a system environment variable
+
[source,powershell]
----
([Environment]::GetEnvironmentVariables("Machine")).TestKey
----
+
[source,powershell]
----
([System.Environment]::GetEnvironmentVariables([System.EnvironmentVariableTarget]::Machine)).TestKey
----
+
[source,powershell]
----
Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" -Name TestKey
----

** Set environment variable permanently +
Run as Administrator
+
[source,powershell]
----
[System.Environment]::SetEnvironmentVariable('TestKey', 'TestValue', 'Machine')
----
+
[source,powershell]
----
[System.Environment]::SetEnvironmentVariable('TestKey', 'TestValue', [System.EnvironmentVariableTarget]::Machine)
----

** Remove environment variable permanently +
Run as Administrator
+
[source,powershell]
----
[System.Environment]::SetEnvironmentVariable('TestKey', '', 'Machine')
----
+
[source,powershell]
----
[System.Environment]::SetEnvironmentVariable('TestKey', '', [System.EnvironmentVariableTarget]::Machine)
----

==== Manage path environment

* Split path
+
[source,powershell]
----
$Env:PATH.split(';')
----

==== Use temporary files

* Get temporary path

** Using `System.IO.Path`: `C:\Users\{username}\AppData\Local\Temp\`
+
[source,powershell]
----
[System.IO.Path]::GetTempPath()
----

** Get from environment variables
+
[source,powershell]
----
$env:TEMP
----

** Get from Windows Registry
+
--
* user environment variables
+
[source,powershell]
----
Get-ItemProperty -Path HKCU:\Environment -Name TEMP
----

* Machine-scoped environment variables
+
[source,powershell]
----
Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" -Name TEMP
----
--

* Create a temporary file
+
[source,powershell]
----
$TempFile = New-TemporaryFile
----

.Examples
* Simple implementation: A temporary file is deleted only if no errors occur.
+
[source,powershell]
----
$TempFile = New-TemporaryFile
Write-Host $TempFile.FullName
Invoke-WebRequest -Uri https://httpbin.org/get -OutFile $TempFile
Get-Content -Path $TempFile
Remove-Item -Path $TempFile
----

* Use `try`, `catch`, and `finally` blocks
+
[source,powershell]
----
try {
    # TempFileCollection manages your temp files and deletes them when it is disposed.
    $tempFiles = [CodeDom.Compiler.TempFileCollection]::new()

    # TempFileCollection doesn't create your temp files for you, you gotta do that yourself.
    $tempFile = New-TemporaryFile

    # and you gotta remember to tell TempFileCollection about this new file.
    $tempFiles.AddFile($tempFile.FullName, $false)

    # now you can use $tempFile
    Write-Host $tempFile.FullName
    Invoke-WebRequest -Uri https://httpbin.org/get -OutFile $tempFile
    Get-Content -Path $tempFile
}
finally {
    # when you dispose the TempFileCollection, it will delete all the files you added to it.
    if ($null -ne $tempFiles) {
        $tempFiles.Dispose()  # Deletes all temp files
    }
}
----

* Use `Register-EngineEvent`
+
[source,powershell]
----
$global:TempFile = New-TemporaryFile
Write-Host ("Temporary file created : Path='{0}'" -f $TempFile.FullName)

# Note: Exit action works only when executed like `powershell test_temp_exit_event.ps1`
# - Exit action does not triggered when executed like `path\to\test_temp_exit_event.ps1`.
# - Exit action does not triggered when closing with the x button.
$null = Register-EngineEvent -SourceIdentifier PowerShell.Exiting -SupportEvent -Action {
    Write-Host ("Remove-Item -Path {0} -Force" -f $TempFile.FullName)
    Remove-Item -Path $TempFile -Force
}

# Now you can use $TempFile
Invoke-WebRequest -Uri https://httpbin.org/get -OutFile $TempFile
Get-Content -Path $TempFile

# Event will trigger here and delete the file
----

.References
* https://stackoverflow.com/questions/34559553/create-a-temporary-directory-in-powershell[Create a temporary directory in PowerShell? - Stack Overflow^]
* https://devblogs.microsoft.com/scripting/create-temporary-files-with-powershell-5/[Create Temporary Files with PowerShell 5 - Scripting Blog^] +
  powershell New-TemporaryFile remove on exit - Google Search
* https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/new-temporaryfile?view=powershell-5.1[New-TemporaryFile (Microsoft.PowerShell.Utility) - PowerShell | Microsoft Learn^]

==== Testing

* pwsh
+
[source,powershell]
----
Install-Module -Name Pester -Force -SkipPublisherCheck
----

* Windows 10
+
[source,powershell]
----
$module = "C:\Program Files\WindowsPowerShell\Modules\Pester"
takeown /F $module /A /R
icacls $module /reset
icacls $module /grant "*S-1-5-32-544:F" /inheritance:d /T
Remove-Item -Path $module -Recurse -Force -Confirm:$false

Install-Module -Name Pester -Force
----

.References
* https://pester.dev/docs/introduction/installation[Installation and Update | Pester^]

=== Array

[source,ps1con]
.Array to TSV
----
PS> @('AAA', 'BBB', 'CCC') -join "`t"
AAA     BBB     CCC
----

=== String

==== Encoding

[source,powershell]
----
[Text.Encoding]::UTF8
[System.Text.Encoding]::GetEncoding('shift_jis')
----

==== Combines multiple strings

* Using `+`
+
[source,powershell]
----
"abc" + "123" + "cdf"
----
+
[source,plaintext]
.Result
----
abc123cdf
----

* Using Join
+
[source,powershell]
----
"abc", "123", "cdf" -join ""
----
+
[source,plaintext]
.Result
----
abc123cdf
----

* Using concat
+
[source,powershell]
----
[System.String]::Concat("abc", "123", "cdf")
----
+
[source,plaintext]
.Result
----
abc123cdf
----

* Variable substitution in strings
+
[source,powershell]
----
PS> $x = "Text"
PS> "This is a `"$x`""
This is a "Text"
----

.References
* https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_join?view=powershell-7.2[about Join - PowerShell | Microsoft Docs^]
* https://docs.microsoft.com/en-us/dotnet/api/system.string?view=net-6.0[String Class (System) | Microsoft Docs^]

==== encoding base64

* encode base64
+
[source,powershell]
.ASCII.GetBytes
----
$someString = "abcdefghijklmnopqrstuvwxyz012345"
[System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($someString))
----
+
[source,powershell]
.UTF8.GetBytes
----
$someString = "abcdefghijklmnopqrstuvwxyz012345"
[System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($someString))
----
+
----
YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXowMTIzNDU=
----
+
[source,powershell]
.decode base64
----
$someStringAsBase64 = "YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXowMTIzNDU="
[System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String($someStringAsBase64))
----

* encode base64
+
[source,powershell]
----
$someString = "こんにちは世界"
[System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($someString))
----
+
----
44GT44KT44Gr44Gh44Gv5LiW55WM
----
+
[source,powershell]
----
$someStringAsBase64 = "44GT44KT44Gr44Gh44Gv5LiW55WM"
[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($someStringAsBase64))
----
+
----
こんにちは世界
----

.Reference
* https://stackoverflow.com/questions/15414678/how-to-decode-a-base64-string[powershell - How to decode a Base64 string? - Stack Overflow^]

==== Generate passwords

[source,powershell]
----
Add-Type -AssemblyName System.web
1..10 | %{ [System.web.security.membership]::GeneratePassword(12, 0) } | Sort-Object
----

==== MD5

* using ComputeHash
+
[source,powershell]
----
$someString = "abcdefghijklmnopqrstuvwxyz012345"
$md5 = [System.Security.Cryptography.MD5]::Create()
[System.Convert]::ToBase64String($md5.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($someString)))
$md5.Dispose()
----

* using ComputeHash (deprecated)
+
[source,powershell]
----
$someString = "abcdefghijklmnopqrstuvwxyz012345"
$md5 = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
[System.Convert]::ToBase64String($md5.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($someString)))
$md5.Dispose()
----

* using Get-FileHash
+
[source,powershell]
----
$someString = "abcdefghijklmnopqrstuvwxyz012345"
$stream = [IO.MemoryStream]::new([Text.Encoding]::UTF8.GetBytes($someString))
$hash = Get-FileHash -InputStream $stream -Algorithm MD5
[System.Convert]::ToBase64String(($hash.Hash -split '([A-F0-9]{2})' | ForEach-Object { if($_) { [System.Convert]::ToByte($_, 16) } }))
$stream.Close()
----

.Results
----
NX6C25NPxF9KJbS4Pci9GQ==
----

=== Flow control statements

* Loop using range
+
[source,powershell]
----
1..5
----
+
[source,powershell]
.ForEach-Object
----
1..5 | % { Write-Output $_ }
----
+
[source,powershell]
.ForEach-Object
----
1..5 | ForEach-Object { Write-Output $_ }
----
+
[source,powershell]
----
foreach($i in 1..5) {
  Write-Output $i
}
----

** Results
+
[source,plaintext]
.Results
----
1
2
3
4
5
----

* Loop using counter
+
[source,powershell]
----
for($i=1; $i -le 5; $i++) {
  Write-Output $i
}
----

** Results
+
[source,plaintext]
.Results
----
1
2
3
4
5
----

* loop with condition
+
[source,powershell]
----
$i = 1
while ($i -le 5) {
  Write-Output $i
  $i += 1
}
----
+
[source,powershell]
----
$i = 1
do {
  Write-Output $i
  $i += 1
} while ($i -le 5)
----

=== External command

* https://adamtheautomator.com/powershell-exit/[How to Use the PowerShell Exit Command and Friends^] +
  powershell exit terminal - Google 検索

==== Get full path to binary in powershell

Equivalent of cmd's "where" in powershell

[source,powershell]
----
Get-Command command_name
gcm command_name
----

.Examples
* show `Path` attribute
+
[source,console]
----
> gcm python | % Path
C:\PythonNNN\python.exe
> (gcm python).Path
C:\PythonNNN\python.exe
----
+
[source,console]
----
> Get-Command -Name python | ForEach-Object Path
C:\PythonNNN\python.exe
> Get-Command -Name python | % Path
C:\PythonNNN\python.exe
> Get-Command -Name python | Select-Object -ExpandProperty Path
C:\PythonNNN\python.exe
> Get-Command -Name python | select -ExpandProperty Path
C:\PythonNNN\python.exe
----
+
[source,console,subs="attributes+"]
--------
> Get-Command -Name python | Select-Object -Property Path

Path
----
C:\PythonNNN\python.exe
--------

* Format-List
+
[source,console]
----
> gcm python | fl


Name            : python.exe
CommandType     : Application
Definition      : C:\PythonNNN\python.exe
Extension       : .exe
Path            : C:\PythonNNN\python.exe
FileVersionInfo : File:             C:\PythonNNN\python.exe
                  InternalName:     Python Console
                  OriginalFilename: python.exe
                  FileVersion:      3.MM.P
                  FileDescription:  Python
                  Product:          Python
                  ProductVersion:   3.MM.P
                  Debug:            False
                  Patched:          False
                  PreRelease:       False
                  PrivateBuild:     False
                  SpecialBuild:     False
                  Language:         ニュートラル言語
----

==== Execute command

[source,powershell]
----
  $process = Start-Process -FilePath ffmpeg.exe -ArgumentList "-i",$_.Name,"-vcodec","copy","-acodec","libopus",$_.Name.Replace('Vorbis', 'Opus') -NoNewWindow -PassThru -Wait
  $process.ExitCode
----

[source,powershell]
----
  $pInfo = New-Object System.Diagnostics.Process
  $pInfo.StartInfo.FileName = "...\ffmpeg.exe"
  $arguments = "-y -i `"$($_.Name)`" -vcodec copy -acodec libopus `"$($_.Name.Replace('Vorbis', 'Opus'))`""
  $pInfo.StartInfo.Arguments = $arguments
  Write-Host $arguments
  $pInfo.StartInfo.UseShellExecute = $false
  $pInfo.StartInfo.CreateNoWindow = $true
  $pInfo.StartInfo.RedirectStandardOutput = $true
  $pInfo.StartInfo.StandardOutputEncoding = [Text.Encoding]::UTF8
  $pInfo.StartInfo.RedirectStandardError = $true
  $pInfo.StartInfo.StandardErrorEncoding = [Text.Encoding]::UTF8
  $pInfo.Start()
  $pInfo.WaitForExit()
  $stdout = $pInfo.StandardOutput.ReadToEnd()
  $stderr = $pInfo.StandardError.ReadToEnd()
  Write-Host $stdout
  Write-Host $stderr
----

=== File system

==== Path

* Combine a path with a child path
+
[source,powershell]
----
Join-Path $env:TEMP -ChildPath foo.txt
----

* https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/join-path?view=powershell-7.2[Join-Path (Microsoft.PowerShell.Management) - PowerShell | Microsoft Docs^]

==== Special folder

* List special folder names
+
[source,powershell]
----
[Environment+SpecialFolder]::GetNames([Environment+SpecialFolder]) | Sort-Object
----
+
[source,plaintext]
.Results
----
AdminTools
ApplicationData
CDBurning
CommonAdminTools
CommonApplicationData
CommonDesktopDirectory
CommonDocuments
CommonMusic
CommonOemLinks
CommonPictures
CommonProgramFiles
CommonProgramFilesX86
CommonPrograms
CommonStartMenu
CommonStartup
CommonTemplates
CommonVideos
Cookies
Desktop
DesktopDirectory
Favorites
Fonts
History
InternetCache
LocalApplicationData
LocalizedResources
MyComputer
MyDocuments
MyMusic
MyPictures
MyVideos
NetworkShortcuts
Personal
PrinterShortcuts
ProgramFiles
ProgramFilesX86
Programs
Recent
Resources
SendTo
StartMenu
Startup
System
SystemX86
Templates
UserProfile
Windows
----

* Application special path
+
[source,powershell]
----
[Environment]::GetFolderPath([Environment+SpecialFolder]::ApplicationData)
----
+
[cols="1a,1a,2a" options="autowidth"]
|===
| Env               | Fields                  | Examples

| `ALLUSERSPROFILE` | `CommonApplicationData` | `C:\ProgramData`
| `AppData`         | `ApplicationData`       | `C:\Users\{username}\AppData\Roaming`
| `LocalAppData`    | `LocalApplicationData`  | `C:\Users\{username}\AppData\Local`
| `SystemRoot`      | `Windows`               | `C:\Windows`
| `TEMP`            |                         | `C:\Users\{username}\AppData\Local\Temp`
| `USERPROFILE`     | `UserProfile`           | `C:\Users\{username}`
|===

* Get profile path
+
[source,powershell]
----
$PROFILE | Get-Member -Type NoteProperty | Format-Table -Wrap
----
+
----
%HOMEPATH%\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
----

.References
* https://superuser.com/questions/217504/is-there-a-list-of-windows-special-directories-shortcuts-like-temp[Is there a list of Windows special directories/shortcuts (like %TEMP%)? - Super User^] +
  windows explorer list of Special Folder - Google Search
* https://pureinfotech.com/list-environment-variables-windows-10/[Complete list of environment variables on Windows 10 - Pureinfotech^] +
  windows variables appdata - Google Search
* https://devblogs.microsoft.com/scripting/the-easy-way-to-use-powershell-to-work-with-special-folders/[The Easy Way to Use PowerShell to Work with Special Folders - Scripting Blog^] +
  powershell Environment+SpecialFolder - Google Search
* https://learn.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?redirectedfrom=MSDN&view=netframework-4.8[Environment.SpecialFolder Enum (System) | Microsoft Learn^]

==== Create/Remove Directory

* Create a directory
+
[source,powershell]
----
New-Item -ItemType Directory foo
----

* Remove a directory
+
[source,powershell]
----
Remove-Item -Path foo
----

* List files
+
[source,ps1con]
----
> Get-ChildItem -Name packages_win64
atomicwrites-1.4.0-py2.py3-none-any.whl
attrs-20.3.0-py2.py3-none-any.whl
colorama-0.4.4-py2.py3-none-any.whl
iniconfig-1.1.1-py2.py3-none-any.whl
packaging-20.9-py2.py3-none-any.whl
pluggy-0.13.1-py2.py3-none-any.whl
py-1.10.0-py2.py3-none-any.whl
pyparsing-2.4.7-py2.py3-none-any.whl
pytest-6.2.2-py3-none-any.whl
toml-0.10.2-py2.py3-none-any.whl
> Get-ChildItem packages_win64 | Where-Object { $ary = $_.Name -Split('-'); Write-Host($ary[0])}
atomicwrites
attrs
colorama
iniconfig
packaging
pluggy
py
pyparsing
pytest
toml
>
----

==== Select-String

* https://tech.sanwasystem.com/entry/2016/07/05/185717[grepコマンドとPowerShellのsls (Select-String)の比較 - Sanwa Systems Tech Blog^] +
  powershell select-string ファイル名 出力しない - Google 検索

.項目
* IgnoreCase LineNumber
* Line
* Filename
* Path

//^

* 1件のファイルから検索をする場合
+
[source,powershell]
----
Select-String "pattern" filename.txt
----

* ファイル名は出力しない
+
[source,powershell]
----
Select-String "pattern" filename | Select Line
----

* CSV出力
+
[source,powershell]
----
Get-ChildItem src -Recurse -Force | Select-String -Pattern 'typing' | Export-Csv -NoTypeInformation result.csv -Encoding UTF8
----

* テーブル表示
+
[source,powershell]
----
Get-ChildItem src -Recurse -Force | Select-String -Pattern 'typing' | Format-Table
----

==== Create/Remove/Copy a file

* Create a new file
+
[source,powershell]
----
New-Item -ItemType File -Path foo.txt
----

* Remove a file
+
[source,powershell]
----
Remove-Item -Path foo.txt
----

** Delete file if exists
+
[source,powershell]
----
$FileName = "D:\PowerShell\ZeroFileSize.txt"
if (Test-Path $FileName) {
  Remove-Item -Force $FileName
}
----

* Copy a file
+
[source,powershell]
----
Copy-Item "C:\foo.txt" -Destination "C:\Temp\"
----
+
.References
* https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/copy-item?view=powershell-7.2[Copy-Item (Microsoft.PowerShell.Management) - PowerShell | Microsoft Docs^]

[source,powershell]
----
New-Item -ItemType File -Path (Join-Path $env:TEMP -ChildPath foo.txt)
Remove-Item -Path (Join-Path $env:TEMP -ChildPath foo.txt)
----

==== Rename/Move file

* Rename single file

** Using `Rename-Item`
+
[source,powershell]
----
$sourceDir = "C:\path to dir"
New-Item -path (Join-Path $sourceDir "apple - a1.txt")
Rename-Item (Join-Path $sourceDir "apple - a1.txt") -NewName "apple - a01.txt"
Remove-Item (Join-Path $sourceDir "apple - a01.txt")
----

** Using `Move-Item`
+
[source,powershell]
----
$sourceDir = "C:\path to dir"
$file1 = New-Item -path (Join-Path $sourceDir "apple - a1.txt")
Move-Item (Join-Path $sourceDir "apple - a1.txt") (Join-Path $sourceDir "apple - a01.txt")
Remove-Item (Join-Path $sourceDir "apple - a01.txt")
----

** Using `Rename-Item` with pipe
+
[source,powershell]
----
$sourceDir = "C:\path to dir"
$file1 = New-Item -path (Join-Path $sourceDir "apple - a1.txt")
$file1 | Rename-Item -NewName "apple - a01.txt"
Remove-Item (Join-Path $sourceDir "apple - a01.txt")
----

** Using `Move-Item` with pipe
+
[source,powershell]
----
$sourceDir = "C:\path to dir"
$file1 = New-Item -path (Join-Path $sourceDir "apple - a1.txt")
$file1 | Move-Item -Destination (Join-Path $sourceDir "apple - a01.txt")
Remove-Item (Join-Path $sourceDir "apple - a01.txt")
----

** Using `MoveTo`
+
[source,powershell]
----
$sourceDir = "C:\path to dir"
$file1 = New-Item -path (Join-Path $sourceDir "apple - a1.txt")
$file1.MoveTo((Join-Path $file1.Directory "apple - a01.txt"))
Remove-Item (Join-Path $sourceDir "apple - a01.txt")
----

* Rename multiple files
+
[source,powershell]
----
include::../src/fs/RenameFiles.ps1[tag=rename-files]
----
+
[subs="quotes"]
.Results
----
... Before
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2022/10/16     12:30              0 apple - *n1*.txt
-a----        2022/10/16     12:30              0 apple - *n2*.txt
-a----        2022/10/16     12:30              0 apple - *n3*.txt
-a----        2022/10/16     12:30              0 banana - n1.txt
-a----        2022/10/16     12:30              0 banana - n2.txt
-a----        2022/10/16     12:30              0 banana - n3.txt
INFO: Rename succeeded.

... After

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2022/10/16     12:30              0 apple - *n01*.txt
-a----        2022/10/16     12:30              0 apple - *n02*.txt
-a----        2022/10/16     12:30              0 apple - *n03*.txt
-a----        2022/10/16     12:30              0 banana - n1.txt
-a----        2022/10/16     12:30              0 banana - n2.txt
-a----        2022/10/16     12:30              0 banana - n3.txt
----

.References
* https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/rename-item?view=powershell-5.1#outputs[Rename-Item (Microsoft.PowerShell.Management) - PowerShell | Microsoft Learn^]
* https://learn.microsoft.com/ja-jp/powershell/module/microsoft.powershell.management/move-item?view=powershell-5.1[Move-Item (Microsoft.PowerShell.Management) - PowerShell | Microsoft Learn^]

==== Join binary

* https://stackoverflow.com/questions/1783554/fast-and-simple-binary-concatenate-files-in-powershell[Fast and simple binary concatenate files in Powershell - Stack Overflow^] +
  powershell join binary files - Google Search

[source,ps1con]
----
gc File1.bin,File2.bin -Encoding Byte -Read 512 | sc new.bin -Encoding Byte
----

==== Archive

[source,powershell]
----
Compress-Archive memo.txt -DestinationPath out.zip
Compress-Archive memo.txt -DestinationPath out.zip -Update -CompressionLevel NoCompression
Compress-Archive memo.txt -DestinationPath out.zip -Update -CompressionLevel Optimal
Compress-Archive memo.txt -DestinationPath out.zip -Update -CompressionLevel Fastest
----

[source,console]
----
> [io.compression.ZipFile]::OpenRead(".\Downloads\out.zip").entries | ? { $_.FullName -match "^[^/]+/*$"} | ft -a FullName,LastWriteTime
FullName LastWriteTime
-------- -------------
memo.txt 2020/12/26 14:11:28 +09:00
----

.References
* https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-7.2[Compress-Archive (Microsoft.PowerShell.Archive) - PowerShell | Microsoft Docs^] +
  Compress-Archive - Google 検索
* https://docs.microsoft.com/ja-jp/dotnet/api/system.io.compression.zipfile.openread?view=net-6.0[ZipFile.OpenRead(String) メソッド (System.IO.Compression) | Microsoft Docs^]
* https://takamaruo.hatenablog.com/entry/2018/10/02/232227[PowerShellでのzipファイルの内容確認・解凍 - たかまるの雑記^]

=== Hardware

==== HDD: Show disk information

* Gets a list of all PhysicalDisk objects
+
[source,powershell]
----
Get-PhysicalDisk
----
+
[source,powershell]
.Show member
----
Get-PhysicalDisk | Get-Member
----

* Gets one or more disks visible to the operating system.
+
[source,powershell]
----
Get-Disk
----
+
[source,powershell]
.Show member
----
Get-Disk | Get-Member
----

.References
* https://docs.microsoft.com/en-us/powershell/module/storage/get-physicaldisk?view=windowsserver2019-ps[Get-PhysicalDisk (Storage) | Microsoft Docs^]
* https://docs.microsoft.com/en-us/powershell/module/storage/get-disk?view=windowsserver2019-ps[Get-Disk (Storage) | Microsoft Docs^]

==== Get all RAW disks, initialize the disks, partition, and format them

. Check disk number column and Partition Style column is `Raw`.
+
[source,powershell]
----
Get-Disk
----

. Start powershell with the Run as Administrator

. Initialize the disks, partition, and format them
+
[source,powershell]
----
Get-Disk | Where-Object PartitionStyle -Eq "RAW" | Initialize-Disk -PartitionStyle GPT -PassThru | New-Partition -DriveLetter H -UseMaximumSize | Format-Volume -NewFileSystemLabel 'backup'
----

==== Initialize disk step by step

. Check disk number
+
[source,console]
----
PS C:\> Get-Disk
----

. Start powershell with the Run as Administrator

. Initialize a disk on disk _2_ using the GPT partition
+
[source,powershell]
----
Initialize-Disk -Number 2 -PartitionStyle GPT
----
+
.References
* https://docs.microsoft.com/en-us/powershell/module/storage/initialize-disk?view=windowsserver2019-ps[Initialize-Disk (Storage) | Microsoft Docs^]

. Create a new partition on disk 2
+
[source,powershell]
----
New-Partition -DiskNumber 2 -DriveLetter H
----
+
.References
* https://docs.microsoft.com/en-us/powershell/module/storage/new-partition?view=windowsserver2019-ps[New-Partition (Storage) | Microsoft Docs^]

. Quick format `H` drives
+
[source,powershell]
----
New-Partition -DiskNumber 2 -DriveLetter H -NewFileSystemLabel 'backup'
----
+
.References
* https://docs.microsoft.com/en-us/powershell/module/storage/format-volume?view=windowsserver2019-ps[Format-Volume (Storage) | Microsoft Docs^]

==== How to convert my hard disk PartitionStyle from GPT back to RAW in Windows 10

[source,powershell]
----
Clear-Disk -Number 2
----

.References
* https://docs.microsoft.com/en-us/powershell/module/storage/clear-disk?view=windowsserver2019-ps[Clear-Disk (Storage) | Microsoft Docs^]

==== BIOS

`msinfo32`

[source,powershell]
.Show serial number
----
Get-CimInstance Win32_BIOS
----

=== Windows

==== Get-WindowsOptionalFeature

* Lists features related to the virtual machine platform
+
[source,powershell]
.Run as Administrator
----
Get-WindowsOptionalFeature -Online -FeatureName *plat*
----

==== Special Environment variables

[cols="1a,1a,2a" options="autowidth"]
|===
| Env               | Examples            | Description

| `ComputerName`    |                     | Your computer name
| `HomeDrive`       | `C:`                |
| `HomePath`        | `\Users\{username}` |
| `SessionName`     | `Console`           |
| `UserDnsDomain`   | | The Fully Qualified Domain Name of the Active Directory domain
| `UserDomain`      |                     | User domain name
| `UserName`        |                     | User name
|===

==== Windows Registry

* Get property
+
[source,powershell]
----
Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Android Studio'
----

** Get User-scoped environment variables
+
[source,powershell]
----
Get-ItemProperty -Path HKCU:\Environment -Name TEMP
----

** Get Machine-scoped environment variables
+
[source,powershell]
----
Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" -Name TEMP
----

** Get .Net versions
+
[source,powershell]
----
Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' -Recurse | Get-ItemProperty -Name version -EA 0 | Where { $_.PSChildName -Match '^(?!S)\p{L}'} | Select PSChildName, version
----

* Get-ChildItem
+
[source,powershell]
----
Get-ChildItem -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall'
----

* Remove registry Key using `Remove-Item`
+
[source,powershell]
----
Remove-Item
----

* Check reboot pending
+
[source,powershell]
----
Test-Path 'HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired'
Test-Path 'HKLM\Software\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending'
----

==== User/Group

* List user accounts
+
[source,powershell]
----
Get-WmiObject Win32_UserAccount
----

* List group
+
[source,powershell]
----
Get-WmiObject Win32_Group
----

==== WSL

* Paste image from Windows host to WSL2
+
[source,shell]
----
powershell.exe '(Get-Clipboard -Format Image).Save("image.png")'
----
+
.References
** https://qiita.com/yugo-yamamoto/items/1538344af52a0bdf4e75[WSL上からWindowsのクリップボードに保存されている画像をpng保存する - Qiita^] +
  vscode wsl2 PasteImage - 検索

* Get IP in WSL
+
[source,powershell]
----
(bash.exe -c "hostname -I").Split(" ")[0]
----

* Invoke web request
+
[source,powershell]
----
Invoke-WebRequest http://localhost:8080/hello
Invoke-WebRequest http://$((bash.exe -c "hostname -I").Split(" ")[0]):8080/hello
----

* Get WSL Interface
+
[source,powershell]
----
Get-NetIPInterface | Where-Object {$_.InterfaceAlias -eq 'vEthernet (WSL)' -and $_.AddressFamily -eq 'IPv4'}
----

==== Show update history
Windows Updateをインストールした後に再起動の状態をPowerShellで確認する

[source,powershell]
----
$Session = New-Object -ComObject "Microsoft.Update.Session"
$Searcher = $Session.CreateUpdateSearcher()
$historyCount = $Searcher.GetTotalHistoryCount()

$Searcher.QueryHistory(0, $historyCount) | Select-Object Date,
  @{
    name="Operation";
    expression={
      switch($_.operation){
        1 {"Installation"}; 
        2 {"Uninstallation"};
        3 {"Other"}
      }
    }
  },
  @{
    name="Status";
    expression={
      switch($_.resultcode) {
        1 {"In Progress"};
        2 {"Succeeded"};
        3 {"Succeeded With Errors"};
        4 {"Failed"};
        5 {"Aborted"}
      }
    }
  }, Title | Out-GridView
----

==== スクリーンセーバーには入らなくなる

[source,powershell]
----
$s = '[DllImport("kernel32.dll")] public static extern int SetThreadExecutionState(long esFlags);'
$w = (Add-Type -MemberDefinition $s -Name 'Win32API' -PassThru)
while ($true) { $w::SetThreadExecutionState(2); Start-Sleep -Seconds 60 }
----
