ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
endif::[]

include::header.adoc[]

== PowerShell examples

=== External command

* https://adamtheautomator.com/powershell-exit/[How to Use the PowerShell Exit Command and Friends^] +
  powershell exit terminal - Google 検索

==== Get full path to binary in powershell

Equivalent of cmd's "where" in powershell

[source,powershell]
----
Get-Command command_name
gcm command_name
----

.Examples
* show `Path` attribute
+
[source,console]
----
> gcm python | % Path
C:\PythonNNN\python.exe
> (gcm python).Path
C:\PythonNNN\python.exe
----
+
[source,console]
----
> Get-Command -Name python | ForEach-Object Path
C:\PythonNNN\python.exe
> Get-Command -Name python | % Path
C:\PythonNNN\python.exe
> Get-Command -Name python | Select-Object -ExpandProperty Path
C:\PythonNNN\python.exe
> Get-Command -Name python | select -ExpandProperty Path
C:\PythonNNN\python.exe
----
+
[source,console,subs="attributes+"]
--------
> Get-Command -Name python | Select-Object -Property Path

Path
----
C:\PythonNNN\python.exe
--------

* Format-List
+
[source,console]
----
> gcm python | fl


Name            : python.exe
CommandType     : Application
Definition      : C:\PythonNNN\python.exe
Extension       : .exe
Path            : C:\PythonNNN\python.exe
FileVersionInfo : File:             C:\PythonNNN\python.exe
                  InternalName:     Python Console
                  OriginalFilename: python.exe
                  FileVersion:      3.MM.P
                  FileDescription:  Python
                  Product:          Python
                  ProductVersion:   3.MM.P
                  Debug:            False
                  Patched:          False
                  PreRelease:       False
                  PrivateBuild:     False
                  SpecialBuild:     False
                  Language:         ニュートラル言語
----

==== Execute command

[source,powershell]
----
  $process = Start-Process -FilePath ffmpeg.exe -ArgumentList "-i",$_.Name,"-vcodec","copy","-acodec","libopus",$_.Name.Replace('Vorbis', 'Opus') -NoNewWindow -PassThru -Wait
  $process.ExitCode
----

[source,powershell]
----
  $pInfo = New-Object System.Diagnostics.Process
  $pInfo.StartInfo.FileName = "...\ffmpeg.exe"
  $arguments = "-y -i `"$($_.Name)`" -vcodec copy -acodec libopus `"$($_.Name.Replace('Vorbis', 'Opus'))`""
  $pInfo.StartInfo.Arguments = $arguments
  Write-Host $arguments
  $pInfo.StartInfo.UseShellExecute = $false
  $pInfo.StartInfo.CreateNoWindow = $true
  $pInfo.StartInfo.RedirectStandardOutput = $true
  $pInfo.StartInfo.StandardOutputEncoding = [Text.Encoding]::UTF8
  $pInfo.StartInfo.RedirectStandardError = $true
  $pInfo.StartInfo.StandardErrorEncoding = [Text.Encoding]::UTF8
  $pInfo.Start()
  $pInfo.WaitForExit()
  $stdout = $pInfo.StandardOutput.ReadToEnd()
  $stderr = $pInfo.StandardError.ReadToEnd()
  Write-Host $stdout
  Write-Host $stderr
----

=== Filesystem

==== Path

* Combine a path with a child path
+
[source,powershell]
----
Join-Path $env:TEMP -ChildPath foo.txt
----

* https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/join-path?view=powershell-7.2[Join-Path (Microsoft.PowerShell.Management) - PowerShell | Microsoft Docs^]

==== Create/Remove Directory

* Create a directory
+
[source,powershell]
----
New-Item -ItemType Directory foo
----
+
* Remove a directory
+
[source,powershell]
----
Remove-Item -Path foo
----

==== Create/Remove/Copy File

* Create a new file
+
[source,powershell]
----
New-Item -ItemType File -Path foo.txt
----

* Remove a file
+
[source,powershell]
----
Remove-Item -Path foo.txt
----

** Delete file if exists
+
[source,powershell]
----
$FileName = "D:\PowerShell\ZeroFileSize.txt"
if (Test-Path $FileName) {
  Remove-Item -Force $FileName
}
----

[source,powershell]
----
New-Item -ItemType File -Path (Join-Path $env:TEMP -ChildPath foo.txt)
Remove-Item -Path (Join-Path $env:TEMP -ChildPath foo.txt)
----

==== Copy files

* Copy a file
+
[source,powershell]
----
Copy-Item "C:\foo.txt" -Destination "C:\Temp\"
----

.References
* https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/copy-item?view=powershell-7.2[Copy-Item (Microsoft.PowerShell.Management) - PowerShell | Microsoft Docs^]

=== Hdd

==== Show disk information

* Gets a list of all PhysicalDisk objects
+
[source,powershell]
----
Get-PhysicalDisk
----
+
[source,powershell]
.Show member
----
Get-PhysicalDisk | Get-Member
----

* Gets one or more disks visible to the operating system.
+
[source,powershell]
----
Get-Disk
----
+
[source,powershell]
.Show member
----
Get-Disk | Get-Member
----

.References
* https://docs.microsoft.com/en-us/powershell/module/storage/get-physicaldisk?view=windowsserver2019-ps[Get-PhysicalDisk (Storage) | Microsoft Docs^]
* https://docs.microsoft.com/en-us/powershell/module/storage/get-disk?view=windowsserver2019-ps[Get-Disk (Storage) | Microsoft Docs^]

==== Get all RAW disks, initialize the disks, partition, and format them

. Check disk number column and Partition Style column is `Raw`.
+
[source,console]
----
PS C:\> Get-Disk
----

. Start powershell with the Run as Administrator

. Initialize the disks, partition, and format them
+
[source,powershell]
----
Get-Disk | Where-Object PartitionStyle -Eq "RAW" | Initialize-Disk -PartitionStyle GPT -PassThru | New-Partition -DriveLetter H -UseMaximumSize | Format-Volume -NewFileSystemLabel 'backup'
----

==== Initialize disk step by step

. Check disk number
+
[source,console]
----
PS C:\> Get-Disk
----

. Start powershell with the Run as Administrator

. Initialize a disk on disk _2_ using the GPT partition
+
[source,powershell]
----
Initialize-Disk -Number 2 -PartitionStyle GPT
----
+
.References
* https://docs.microsoft.com/en-us/powershell/module/storage/initialize-disk?view=windowsserver2019-ps[Initialize-Disk (Storage) | Microsoft Docs^]

. Create a new partition on disk 2
+
[source,powershell]
----
New-Partition -DiskNumber 2 -DriveLetter H
----
+
.References
* https://docs.microsoft.com/en-us/powershell/module/storage/new-partition?view=windowsserver2019-ps[New-Partition (Storage) | Microsoft Docs^]

. Quick format `H` drives
+
[source,powershell]
----
New-Partition -DiskNumber 2 -DriveLetter H -NewFileSystemLabel 'backup'
----
+
.References
* https://docs.microsoft.com/en-us/powershell/module/storage/format-volume?view=windowsserver2019-ps[Format-Volume (Storage) | Microsoft Docs^]

==== How to convert my hard disk PartitionStyle from GPT back to RAW in Windows 10

[source,powershell]
----
Clear-Disk -Number 2
----

.References
* https://docs.microsoft.com/en-us/powershell/module/storage/clear-disk?view=windowsserver2019-ps[Clear-Disk (Storage) | Microsoft Docs^]
