name: Convert AsciiDoc documents to HTML

on:
  push:
    branches: [ "main" ]

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: convert asciidoc to html
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Get build container
      id: adocbuild
      uses: tonynv/asciidoctor-action@master
      with:
          program: "cd docs && make adoc"
    - name: copy .gitignore file
      uses: canastro/copy-file-action@master
      with:
        source: "gh-pages.gitignore"
        target: "dist/.gitignore"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/
